import { addImage, deleteImage, addComment, deleteComment, limit_image, getImageIds, getComments, getUsers, signout } from "./api.mjs";

let skip = 0;

let comment_skip = 0;

let everything = false;

let temp = comment_skip;

//This file copied and modified from the starter code of lab 2, lab 4, and HW1

//Prevents the page to be loaded from cache when user press the back nevigation button to get from credit page back to main page
//This snippet of code is generated by: https://stackoverflow.com/questions/8788802/prevent-safari-loading-from-cache-when-back-button-is-clicked and https://stackoverflow.com/questions/9046184/reload-the-site-when-reached-via-browsers-back-button, some googling is done to keep the methods up-to-date, performance nevigation is depricated
const perfEntries = performance.getEntriesByType("navigation");
if (perfEntries.length > 0) {
    const navType = perfEntries[0].type;

    if (navType === "back_forward") {
        window.location.reload();
    }
}

document
    .getElementById("create_image_form")
    .addEventListener("submit", function (e) {
        // prevent from refreshing the page on submit
        e.preventDefault();
        // read form elements


        //Fetch the information input by the user
        const url = document.getElementById("image_input").files[0];
        const title = document.getElementById("title").value;

        //Store info
        addImage(title, url, start, onError);

        // clean form
        document.getElementById("create_image_form").reset();

    });

document.getElementById("signout").addEventListener("click", function (e) {
    signout(onError, function () {
        window.location.href = "/";
    })
});

start();



function start() {
    getUsers(userhandle, onError);
}

function userhandle(users) {

    //Present the name of current user
    const title = document.getElementById("web_title");

    title.innerHTML = `Welcome, ${users[0]}`;

    //Populating drop down using array, the code is generated by: https://stackoverflow.com/questions/9895082/javascript-populate-drop-down-list-with-array
    const dropdown = document.getElementById('dropdown');

    dropdown.innerHTML = "";
    // Loop through the array and create options
    users.forEach(item => {
        const option = document.createElement('option'); // create an option element
        option.value = item;   // set the value attribute
        option.textContent = item; // set the visible text
        dropdown.appendChild(option); // add option to dropdown
    });

    dropdown.addEventListener("change", function (e) {
        const value = e.target.value;
        document.getElementById("image_sec").innerHTML = "";
        document.getElementById("messages").innerHTML = ``;
        return initialize(value);
    })
    initialize(users[0]);
}
function initialize(author) {
    everything = false;
    getImageIds(loadLatestImage, onError, skip, author);
}

function loadLatestImage(ids) {

    if (ids == null || ids.length == 0) {
        return;
    }

    if (ids.length < limit_image) {
        everything = true;
    }

    loadImage(ids, 0);
}

function loadImage(images, index) {
    if (images.length == 0 || images == null) {
        return;
    }
    document.getElementById("image_sec").innerHTML = "";
    document.getElementById("messages").innerHTML = ``;

    //Reset current comments skip count to 0
    comment_skip = 0;

    //Reset commetn variable
    temp = comment_skip;

    // create a new message element
    const elmt = document.createElement("div");
    elmt.className = "image_container";

    const image = images[index];


    //The following two lines are created by https://stackoverflow.com/questions/10599148/how-do-i-get-the-current-time-only-in-javascript
    const date = new Date(image.createdAt);
    const time = date.toLocaleString();
    elmt.innerHTML = `

    

    <div class = "gallery_header">
        <h2 >${image.author}'s gallery</h2>
    </div>

        <div class="img_title"> ${image.title} <br> posted on: ${time}</div>
        
        <div class="image">
            <button type="button" class="btn" id="left">◀</button>
            <img src="/api/images/${image._id}" alt="User image" width="300" height="300">
            <button type="button" class="btn" id="right">▶</button>
        </div> 

        <button type="button" class="dele_btn" id="delete">Delete this image</button>

        <form id="comment_form">

            <input type="text" id="comment" class="comment" placeholder="Enter your comment" required />

            <button type="submit" class="btn" id="add_comment">Add comment</button>

         </form> 

    `;
    // add this element to the document
    document.getElementById("image_sec").append(elmt);

    document.getElementById("left").addEventListener("click", function (e) {
        loadOlderImage(images, index);
    });

    document.getElementById("right").addEventListener("click", function (e) {
        loadNewerImage(images, index);
    });

    document.getElementById("delete").addEventListener("click", function (e) {
        deleteImage(image._id, onError, function(){
            updateDomImg(index, images);
        });

        
    });

    document.getElementById("comment_form").addEventListener("submit", function (e) {
        e.preventDefault();

        const comment = document.getElementById("comment").value;

        document.getElementById("comment_form").reset();

        comment_skip = 0; //When a new comment is added, show the newest comments

        addComment(image._id, comment, addCnthandler, onError);

    });

    loadLatestComments(image._id);
}

function updateDomImg(index, images) {
    document.getElementById("image_sec").innerHTML = "";
    document.getElementById("messages").innerHTML = ``;

    images.splice(index, 1);

    if (images.length == 0) {
        return loadOlderImage(images, 0);
    }

    let newIndex = index;
    if (newIndex >= images.length) {
        newIndex = images.length - 1; // If we deleted the last one, move to previous
    }
    if (newIndex < 0) {
        newIndex = 0; // If index was 0, stay at 0 after deletion
    }

    loadImage(images, newIndex);
}


function loadOlderImage(images, index) {
    if (index >= images.length - 1) {
        if (everything) {
            return;
        }
        skip += images.length;
        return initialize();
    }
    loadImage(images, index + 1);
}

function loadNewerImage(images, index) {
    if (index <= 0) {
        if (skip === 0) {
            return;
        }
        skip -= images.length;

        if (skip < 0) {
            skip = 0;
        }
        return initialize();
    }
    loadImage(images, index - 1);
}


function addCnthandler(res) {
    loadLatestComments(res.imageId);
}

function loadLatestComments(imageId) {
    getComments(imageId, comment_skip, loadComments, onError);
}

function loadComments(comments) {

    //If nothing is fetched, then it means the current skip is not valid (too far), get back to the old element
    if (comments == null || comments.length == 0) {
        comment_skip = temp;
        return;
    }


    document.getElementById("messages").innerHTML = ``;

    const imageId = comments[0].imageId;

    let comment_sec = document.getElementById("messages");
    for (let i = 0; i < comments.length; i++) {
        const elmt = document.createElement("div")
        const date = new Date(comments[i].createdAt);
        const time = date.toLocaleString();
        elmt.className = "message";
        elmt.innerHTML = `
        <div class="message_user">
            <div class="message_username">${comments[i].author}</div>
            <div class="message_username">Posted on: ${time}</div>
        </div>
        <div class = "message_user">
            <div class="message_content">${comments[i].content}</div>
            <div class="delete-icon icon" id="delete${i}"></div>
        </div>
    `;
        comment_sec.append(elmt);

        document.getElementById("delete" + i).addEventListener("click", function (e) {
            deleteComment(comments[i]._id, onError, function(){
                updateDomCmt(i, comments);
            });
        });
    }
    const nevi = document.createElement("div");
    nevi.innerHTML = `
            <button type="button" class="btn" id="forward">◀</button>
           
            <button type="button" class="btn" id="backward">▶</button>`;



    comment_sec.append(nevi);

    document.getElementById("forward").addEventListener("click", function (e) {
        loadNewerComments(imageId, comments.length);
    });

    document.getElementById("backward").addEventListener("click", function (e) {
        loadOlderComments(imageId, comments.length);
    });
}

function updateDomCmt(i, comments){
    const imageId = comments[i].imageId;
            comments.splice(i, 1);
            if (comments.length == 0) {
                //If the current image array is all out, default to print the newst elements
                document.getElementById("messages").innerHTML = ``;
                comment_skip = 0;
                return loadLatestComments(imageId);
            }
            return loadLatestComments(imageId);
}

function loadOlderComments(imageId, length) {

    temp = comment_skip;

    comment_skip = comment_skip + 10;

    getComments(imageId, comment_skip, loadComments, onError);
}

function loadNewerComments(imageId, length) {
    temp = comment_skip;

    comment_skip = comment_skip - 10;

    if (comment_skip <= 0) {
        comment_skip = 0;
    }

    getComments(imageId, comment_skip, loadComments, onError);
}



const button = document.getElementById("hide");
const fields = document.getElementById("fields");

//This snippet of code is generated by https://www.w3schools.com/css/css3_animations.asp
button.addEventListener("click", () => {
    fields.classList.toggle("show");
    button.textContent = fields.classList.contains("show") ? "Hide" : "Expand";
});

function onError(err) {
    console.error("[error]", err);
    let error_box = document.querySelector("#error_box");
    error_box.innerHTML = err.message;
    error_box.style.visibility = "visible";
    // Hide after 3 seconds (3000 ms)
    setTimeout(() => {
        error_box.style.visibility = "hidden";
        error_box.innerHTML = ""; // optional: clear text
    }, 2000);
}